[[main]]
none = "none"

[[main]]
name = "Ilustracje"
pageRef = "art"
identifier = "3yRSzr3A8F"
weight = 10

[[main]]
name = "Zalążki"
pageRef = "seeds"
identifier = "3yRSzr3A8D"
weight = 20

[[main]]
name = "Przeglądaj"
weight = 30

[[main]]
parent = "Przeglądaj"
name = "Tagi"
pageRef = "tags"
identifier = "24BZL6Odw6"
weight = 30

[[main]]
parent = "Przeglądaj"
name = "Autorów"
pageRef = "authors"
identifier = "LD7z6Qopgw"
weight = 40

[[main]]
name = "Wydarzenia"
weight = 45

[[main]]
parent= "Wydarzenia"
name = "Art Collab 2025 [ENG]"
url = "/pages/andrewisms-art-collab-2025"
identifier = "3yRGzr3A8D"
weight = 10

[[main]]
name = "Więcej o..."
weight = 50

[[main]]
parent = "Więcej o..."
name = "Bibliotece"
pageRef = "/pages/about"
weight = 1

[[main]]
parent = "Więcej o..."
name = "Solarpunku"
url = "/pl/essays/what-is-solarpunk"
weight = 2

[[main]]
parent = "Więcej o..."
name = "Manifeście"
url = "/pl/essays/solarpunk-manifesto"
weight = 3

[[main]]
parent = "Więcej o..."
name = "podkaście Solarpunk Prompts"
url = "https://podcast.tomasino.org/@SolarpunkPrompts"
weight = 4

[[main]]
parent = "Więcej o..."
name = "kuratorze"
url = "https://alxd.org/"
weight = 5

[[main]]
parent = "Więcej o..."
name = "Jak się przyłączyć?"
pageRef = "/pages/contribute"
weight = 10

[[main]]
pre = "rss"
url = "/pl/index.xml"
identifier = "someRSShere"
weight = 60

[[footer]]
none = "none"

[[footer]]
name = "Jak się przyłączyć?"
pageRef = "/pages/contribute"
identifier = "Wz0vblbVYr"
weight = 1

[[footer]]
name = "Kontakt"
url = "storySeedLibrary@alxd.org"
identifier = "contactUs"
weight = 2
